# Generated by Django 4.1.4 on 2023-01-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access_Record',
            new_name='AccessRecord',
        ),
    ]
